<a href="https://colab.research.google.com/github/pranav-sirnapalli/3bit_up_down_counter/blob/main/tensor_pt1_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

In [74]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


Intorduction to Tensors

Creating tensors

PyTorch tensors created using torch.tensor()

In [75]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [76]:
# Get tensor back as Python int
scalar.item()

7

In [77]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [78]:
vector.ndim

1

In [79]:
vector.shape

torch.Size([2])

In [80]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [81]:
MATRIX.ndim

2

In [82]:
MATRIX[0]

tensor([7, 8])

In [83]:
MATRIX.shape

torch.Size([2, 2])

In [84]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [85]:
TENSOR.ndim

3

In [86]:
TENSOR.shape

torch.Size([1, 3, 3])

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers`

In [87]:
# Create a random tensor of size
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.5412, 0.5054, 0.8362, 0.3564],
        [0.4440, 0.4019, 0.1216, 0.8608],
        [0.2005, 0.3935, 0.6019, 0.7286]])


In [88]:
random_tensor.ndim

2

In [89]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeroes and ones

In [90]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [91]:
zeros * random_tensor # So if you ever need to mask out a column of values just create
# one column of 0s and multiply with the tensor it will mask out.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [92]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
ones.dtype

torch.float32

In [94]:
random_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like

In [95]:
# use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# another use of torch.arange()
one_to_ten = torch.arange(start = 0, end = 1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [97]:
# Creating tensors like
# used to replicate a particular shape of tensor
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
**Note:**Tensor datatypes is one of the 3 big errors you will run into with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [98]:
# Float 32 tensor, float 32 is a default type
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensor (eg:float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [99]:
float_32_tensor.dtype

torch.float32

In [100]:
# Setting it as float 16
float_32_tensor = torch.tensor([2.0, 4.0, 6.0], dtype=torch.float32)
float_32_tensor

tensor([2., 4., 6.])

In [101]:
float_32_tensor.dtype

torch.float32

In [102]:
float_16_tensors = float_32_tensor.type(torch.float16)
float_16_tensors

tensor([2., 4., 6.], dtype=torch.float16)

In [103]:
res = float_16_tensors * float_32_tensor
res.dtype

torch.float32

In [104]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [105]:
float_32_tensor * int_32_tensor

tensor([ 6., 24., 54.])

In [106]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [107]:
float_32_tensor * int_32_tensor

tensor([ 6., 24., 54.])

Getting information from tensors
1. Tensors not right datatype- to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get device from a tensor, can use tensor.device

In [108]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1768, 0.8315, 0.6143, 0.2352],
        [0.3390, 0.8591, 0.6561, 0.1859],
        [0.1153, 0.2502, 0.8578, 0.5874]])

In [109]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.1768, 0.8315, 0.6143, 0.2352],
        [0.3390, 0.8591, 0.6561, 0.1859],
        [0.1153, 0.2502, 0.8578, 0.5874]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on: cpu


In [110]:
### Manipulating Tensors(tensor operation basics):
# 1. Addition
# 2. Subtraction
# 3. Multiplication(element-wise)
# 4. Division
# 5. Matrix multiplication

# tensor creation
tensor = torch.tensor([1, 2, 3])
# tensor Addtion
print(tensor + 10)
# tensor Multiplication
print(tensor * 10)
# tensor Subtraction
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [111]:
# Build in multiplication
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [112]:
# Build in addition
torch.add(tensor, 10)

tensor([11, 12, 13])

In [113]:
### Matrix multiplication

# Two ways to perform multiplication in neural networks and deep learning
# 1. Element-wise
# 2. Matrix multiplication (dot product)

# There are two main rules that need to be satisfied to perform matrix
# multiplication:
# 1. Inner dimensions must match:
#  - (3, 2) @ (3, 2) won't work
#  - (2, 3) @ (3, 2) will work
#  - (3, 2) @ (2, 3) will work

# 2. The resulting matrix should have shape of outer dimensions
# - (2, 3) @ (3, 2) will work -> (2, 2)
# - (3, 2) @ (2, 3) will work -> (3, 3)
#

#1. Element-wise
print("Element wise multiplication: ")
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")



Element wise multiplication: 
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [114]:
#2. Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [115]:
### One of the most common errors in deep learning: shape errors
### If the matrices are same shape put one using transpose

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

tensor_B
transpose_B = tensor_B.T
transpose_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [116]:
### Finding the min, max, mean, sum etc(tensor aggregation)

# Required tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [117]:
# Min of a tensor
torch.min(x)

tensor(0)

In [118]:
# Find the max
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [119]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [120]:
# Find the sum
torch.sum(x)

tensor(450)

In [121]:
# Finding position of min and max
# Returns index of the minimum and maximum value.
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaphing, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Returns a veiw of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)

* Squeeze - removes all `l` dimensions from a tensor

* Unsqueeze - add a `l` dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [122]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [123]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [124]:
# add extra dimension in other direction
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [125]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)


In [126]:
# putting the value of z
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [127]:
# changing z changes x[because a view of a tensor shares the same memory as the original]
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [128]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [129]:
x_stacked_vert = torch.stack([x, x, x, x], dim=1)
x_stacked_vert

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [130]:
# torch.squeeze() - Removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [131]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [132]:
x_reshaped.shape

torch.Size([1, 9])

In [133]:
# As squeeze removed one dimension can be seen below
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [134]:
x_reshaped.squeeze().shape

torch.Size([9])

In [135]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") # [color_channels, height, width]

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [136]:
x_original[:, :, 0]

tensor([[0.2892, 0.4274, 0.1207,  ..., 0.1646, 0.9635, 0.9265],
        [0.6147, 0.8673, 0.1459,  ..., 0.0292, 0.8202, 0.0356],
        [0.7760, 0.7610, 0.4732,  ..., 0.4473, 0.3970, 0.0301],
        ...,
        [0.1998, 0.0069, 0.8096,  ..., 0.3775, 0.7465, 0.3277],
        [0.2040, 0.5646, 0.7314,  ..., 0.6759, 0.1821, 0.6706],
        [0.5168, 0.2468, 0.1267,  ..., 0.1672, 0.5593, 0.1468]])

In [137]:
x_original[0, :, :]

tensor([[2.8925e-01, 4.7336e-01, 4.0146e-02],
        [4.2741e-01, 1.1188e-01, 5.2078e-01],
        [1.2072e-01, 2.0894e-01, 1.3562e-01],
        [3.1927e-02, 7.2614e-01, 2.0458e-01],
        [4.1906e-01, 9.7630e-01, 1.2923e-01],
        [3.9254e-01, 9.6922e-01, 1.6253e-01],
        [5.0179e-01, 2.9614e-01, 8.9210e-01],
        [6.1060e-01, 6.5250e-01, 5.7573e-02],
        [7.2389e-01, 1.5749e-02, 6.3529e-01],
        [8.8267e-01, 9.5813e-01, 5.7199e-01],
        [2.8355e-01, 1.3300e-02, 3.3896e-01],
        [9.8945e-01, 6.4682e-01, 7.4319e-01],
        [9.0394e-01, 3.5666e-02, 7.8104e-01],
        [6.9177e-01, 3.0891e-01, 7.7946e-01],
        [4.9880e-01, 8.4978e-01, 8.5917e-01],
        [7.8506e-01, 5.8014e-01, 7.7533e-01],
        [4.3319e-01, 7.7650e-01, 8.5124e-02],
        [5.4260e-01, 9.1714e-01, 9.9113e-01],
        [1.6419e-01, 4.4837e-01, 3.1827e-02],
        [1.4598e-01, 2.3736e-02, 4.5722e-01],
        [8.6875e-01, 8.8530e-01, 4.0490e-01],
        [9.6518e-01, 2.3739e-01, 2

In [138]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

Indeexing(selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [139]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [140]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [141]:
# Let's index on the middle bracket (dim = 1)
x[0, 0]

tensor([1, 2, 3])

In [142]:
# Lets index on inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [143]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [144]:
# Get all values of the 0 dimension but only the 1 value index of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [145]:
# Get index 0 or 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [146]:
# Index on x to return 9
print(x[0][2][2])
# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])
